"""Initial schema

Revision ID: 9de0df49b6bd
Revises: 
Create Date: 2026-08-05 21:56:05.540830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de0df49b6bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agencies_id'), 'agencies', ['id'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('agence_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('date_desactivation', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agence_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('agence_id', sa.Integer(), nullable=True),
    sa.Column('actif', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agence_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pickup_slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_bordereau', sa.String(length=50), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('date_tournee', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=True),
    sa.Column('statut', sa.String(length=20), server_default='ouvert', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickup_slips_id'), 'pickup_slips', ['id'], unique=False)
    op.create_index(op.f('ix_pickup_slips_numero_bordereau'), 'pickup_slips', ['numero_bordereau'], unique=True)
    op.create_table('pickups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_slip_id', sa.Integer(), nullable=False),
    sa.Column('numero_declaration', sa.String(length=100), nullable=True),
    sa.Column('client_nom', sa.String(length=100), nullable=False),
    sa.Column('client_telephone', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('nombre_colis', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure', sa.Time(), nullable=False),
    sa.Column('observations', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pickup_slip_id'], ['pickup_slips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pickups_id'), 'pickups', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickups_id'), table_name='pickups')
    op.drop_table('pickups')
    op.drop_index(op.f('ix_pickup_slips_numero_bordereau'), table_name='pickup_slips')
    op.drop_index(op.f('ix_pickup_slips_id'), table_name='pickup_slips')
    op.drop_table('pickup_slips')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_agencies_id'), table_name='agencies')
    op.drop_table('agencies')
    # ### end Alembic commands ###
