"""add_performance_indexes

Revision ID: f6ac80224bb0
Revises: 9de0df49b6bd
Create Date: 2026-08-11 16:21:28.814395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ac80224bb0'
down_revision: Union[str, Sequence[str], None] = '9de0df49b6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pickup_slips_agency_id'), 'pickup_slips', ['agency_id'], unique=False)
    op.create_index(op.f('ix_pickup_slips_date_tournee'), 'pickup_slips', ['date_tournee'], unique=False)
    op.create_index(op.f('ix_pickup_slips_driver_id'), 'pickup_slips', ['driver_id'], unique=False)
    op.create_index(op.f('ix_pickups_date'), 'pickups', ['date'], unique=False)
    op.create_index(op.f('ix_pickups_pickup_slip_id'), 'pickups', ['pickup_slip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pickups_pickup_slip_id'), table_name='pickups')
    op.drop_index(op.f('ix_pickups_date'), table_name='pickups')
    op.drop_index(op.f('ix_pickup_slips_driver_id'), table_name='pickup_slips')
    op.drop_index(op.f('ix_pickup_slips_date_tournee'), table_name='pickup_slips')
    op.drop_index(op.f('ix_pickup_slips_agency_id'), table_name='pickup_slips')
    # ### end Alembic commands ###
